# yaml-language-server: $schema=https://raw.githubusercontent.com/kjellberg/mrsk/validate-with-json-schema/lib/mrsk/configuration/schema.yaml

# Name of your application. Used to uniquely configure containers.
service: kamal-nodejs-template

# Name of the container image.
image: timkochdev/kamal-nodejs-template

# Deploy to these servers.
servers:
  - 168.119.124.184

builder:
  target: prod

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: timkochdev

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .env).
# Remember to run `kamal env push` after making changes!
env:
  clear:
    NODE_ENV: production
    POSTGRES_HOST: 168.119.124.184
    POSTGRES_USER: postgres
    POSTGRES_DB: example
  secret:
    - POSTGRES_PASSWORD

# Use accessory services (secrets come from .env).
accessories:
  db:
    image: postgres
    host: 168.119.124.184
    port: 5432
    env:
      clear:
        POSTGRES_DB: example
      secret:
        - POSTGRES_PASSWORD

# Configure custom arguments for Traefik. Be sure to reboot traefik when you modify it.
traefik:
  args:
    accesslog: true
    accesslog.format: json
    api.dashboard: true
    api.insecure: true
  options:
    publish:
      - 8080:8080

# Configure a custom healthcheck (default is /up on port 3000)
healthcheck:
  cmd: "echo 'hallo tim'"
